# Railway deployment configuration
# This file tells Railway how to build and deploy your Next.js app

# Build configuration
[build]
  builder = "nixpacks"

# Environment variables (set these in Railway dashboard)
[env]
  NODE_ENV = "production"
  
# Health check
[health]
  path = "/api/test"
  
# Service configuration
[services.web]
  # Railway supports larger payloads out of the box
  # No need for special configuration for 100MB files
